import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case zhHans = "zh-Hans"
    case en = "en"

    nonisolated static let storageKey = "paodekuai.native.language"

    var id: String { rawValue }
    var speechCode: String {
        switch self {
        case .zhHans: return "zh-CN"
        case .en: return "en-US"
        }
    }

    var displayName: String {
        switch self {
        case .zhHans: return "中文"
        case .en: return "English"
        }
    }
}

nonisolated enum L10n {
    private static let zhHans: [String: String] = [
        "app_title": "湖南跑得快（单机）",
        "hand_no_format": "第%d手",
        "player_me": "我方",
        "player_left": "上家",
        "player_right": "下家",
        "score_me_format": "我方 %d",
        "score_left_format": "上家 %d",
        "score_right_format": "下家 %d",
        "remaining_cards_format": "剩余 %d 张",
        "table_pile": "桌面牌堆",
        "table_waiting": "等待出牌",
        "recent_play_format": "最近出牌：%@",
        "my_hand": "我的手牌",
        "selected_count_format": "已选 %d",
        "play": "出牌",
        "next_hand": "下一手",
        "pass": "过牌",
        "declare_single": "报单",
        "new_game": "新对局",
        "settings": "设置",
        "rules": "设置/规则",
        "language": "语言",
        "round_result": "本手结算",
        "round_history": "结算历史",
        "round_history_empty": "暂无结算记录",
        "move_history": "出牌记录",
        "move_history_empty": "暂无出牌记录",
        "move_play_format": "第%d手 %@ 出牌 %@",
        "move_pass_format": "第%d手 %@ 过牌",
        "move_reason_suffix_format": "（AI: %@）",
        "round_col_hand": "手数",
        "round_col_me": "我方",
        "round_col_left": "上家",
        "round_col_right": "下家",
        "round_result_line_format": "第%d手 %@：我方%+d 上家%+d 下家%+d",
        "hint_tap_new_game": "点击“新对局”开始",
        "hint_new_round_first_format": "新一手开始，%@先手",
        "hint_first_lead_no_pass": "先手不能过牌",
        "hint_must_beat_no_pass": "有大必出，不能过牌",
        "hint_must_beat_cycle_format": "有大必出，已为你选择第%d/%d组可出牌",
        "hint_drag_select_ready": "长按后可拖动批量选牌",
        "hint_first_turn_need_3s": "首手必须包含黑桃3",
        "hint_must_play_highest_single_when_next_one_card": "下家仅剩1张时，出单牌必须出当前最大单牌",
        "hint_cannot_beat_top": "不能压过桌面牌",
        "hint_played_cards_format": "%@出牌：%@",
        "hint_two_pass_reset_format": "两家过牌，%@重新领出",
        "hint_player_pass_format": "%@过牌",
        "voice_player_cannot_beat_format": "%@要不起",
        "hint_round_finish_format": "本手结束：%@获胜",
        "hint_restored_local_state": "已恢复本地进度",
        "hint_action_ready": "请选择要出的牌",
        "hint_declared_single": "已报单，单牌可压时自动出牌，其余自动过牌",
        "hint_waiting_player_format": "等待%@出牌",
        "voice_declare_single": "我方报单",
        "hint_bomb_must_play": "当前只有炸弹可压，必须出炸弹",
        "confirm_new_game_title": "开始新对局？",
        "confirm_new_game_message": "当前对局进度会被覆盖。",
        "confirm": "确认",
        "cancel": "取消",
        "rules_page_title": "设置与规则",
        "tab_rules": "规则",
        "tab_settings": "设置",
        "rules_deck_title": "1. 牌组与发牌",
        "rules_deck_body": "使用湖南跑得快 48 张牌（去掉红桃2、方块2、梅花2、方块A），三家各 16 张。",
        "rules_turn_title": "2. 出牌顺序",
        "rules_turn_body": "整局第一手必须包含黑桃3；之后按顺序接牌。两家都过牌后，最后出牌者重新领出。",
        "rules_play_title": "3. 合法牌型",
        "rules_play_body": "支持：单张、对子、顺子、连对、三带二、飞机带翅膀、炸弹。",
        "rules_compare_title": "4. 牌型比较",
        "rules_compare_body": "同牌型且同张数才可比较主牌大小；炸弹可压非炸弹，炸弹之间比较点数。",
        "rules_must_title": "5. 过牌限制",
        "rules_must_body": "若你手中存在可压过当前桌面牌的牌，则不可选择“过牌”。湖南常规下：若仅炸弹可压，则必须出炸弹；若有其他可压牌，可不出炸弹。",
        "rules_score_title": "6. 计分规则",
        "rules_score_body": "每手结束后，赢家获得两家罚分之和。输家罚分：剩1张及以下记0，剩15张记15，剩16张记30，其余按剩余张数计。炸弹单独计分：成功炸住时，出炸弹者+20，其余两家各-10；若被更大炸弹反压，前一炸弹作废，由更大炸弹按同规则计分。结算历史会对被炸方标记💣。",
        "rules_setting_title": "7. 牌局设置",
        "rules_setting_body": "可配置三带一、三不带、仅炸可压时必出炸弹以及常见规则预设。",
        "strategy_title": "策略提示",
        "strategy_1_title": "先跑为主",
        "strategy_1_body": "尽量把散牌和低点数对子提前处理，减少最后被卡手的概率。",
        "strategy_2_title": "留意报单",
        "strategy_2_body": "下家只剩一张时，单牌要优先压住，避免把胜利机会送出去。",
        "strategy_3_title": "炸弹别急",
        "strategy_3_body": "炸弹既能抢回出牌权，也会影响结算分，最好在能改变局势时使用。",
        "strategy_4_title": "善用顺子",
        "strategy_4_body": "连续牌能快速减少手牌数量，但要避免拆掉后续能压制对手的组合。",
        "rules_preset": "规则预设",
        "rules_preset_hunanClassic": "湖南常规",
        "rules_preset_relaxed": "宽松模式",
        "rules_preset_bombPriority": "仅炸必出",
        "rules_preset_custom": "自定义",
        "rules_allow_triple_with_one": "允许三带一",
        "rules_allow_triple_without_wing": "允许三不带",
        "rules_bomb_must_play": "仅炸可压时必出炸弹",
        "rules_ai_tuning_title": "AI 调参（开发）",
        "rules_ai_tuning_danger_threshold": "危险阈值（报单判定）",
        "rules_ai_tuning_avoid_bomb_turns": "保炸阈值（剩余手数）",
        "rules_ai_tuning_history_limit": "记录条数上限",
        "rules_selfplay_title": "自博弈导出（开发）",
        "rules_selfplay_enable": "开启后自动跑并导出汇总",
        "rules_selfplay_hands": "自博弈手数",
        "rules_selfplay_share_summary": "分享汇总 JSON",
        "rules_selfplay_share_unavailable": "暂无可分享文件，请先完成一次自博弈导出",
        "rules_selfplay_share_latest_log": "分享最新对局日志 JSON",
        "rules_selfplay_share_latest_log_unavailable": "暂无最新对局日志，请先完成至少一手对局",
        "rules_selfplay_share_detail": "分享自博弈完整明细 JSON",
        "rules_selfplay_share_detail_unavailable": "暂无自博弈明细，请先完成一次自博弈",
        "selfplay_status_running_format": "自博弈运行中：%d 手...",
        "selfplay_status_done_format": "自博弈完成，已导出：%@",
        "selfplay_status_done_with_detail_format": "自博弈完成，汇总：%@；明细：%@",
        "selfplay_status_done_detail_only_format": "自博弈完成，已导出明细：%@",
        "selfplay_status_failed": "自博弈导出失败",
        "welcome_title": "湖南跑得快",
        "welcome_subtitle": "原汁原味 · 经典玩法",
        "welcome_start_game": "开始游戏",
        "voice_on": "语音开",
        "voice_off": "语音关",
        "invalid_no_selection": "未选择牌",
        "invalid_shape": "牌型不合法",
        "voice_pair_prefix": "对",
        "voice_bomb_suffix": "炸弹",
        "voice_straight": "顺子",
        "voice_triple": "三张",
        "voice_triple_with_one": "三带一",
        "voice_triple_with_two": "三带二",
        "voice_airplane_with_wings": "飞机带牌",
        "voice_consecutive_pairs": "连对",
        "voice_rank_a": "尖",
        "voice_rank_t": "十",
        "voice_rank_2": "二",
        "voice_rank_j": "勾",
        "voice_rank_q": "圈",
        "speech_round_finish_format": "%@先跑完。",
        "privacy_policy_title": "隐私政策",
        "privacy_policy_url": "https://paodekuai.pokerjudge.com/privacy-zh.html",
        "about_title": "关于"
    ]

    private static let en: [String: String] = [
        "app_title": "Hunan Paodekuai (Solo)",
        "hand_no_format": "Hand %d",
        "player_me": "Me",
        "player_left": "Left",
        "player_right": "Right",
        "score_me_format": "Me %d",
        "score_left_format": "Left %d",
        "score_right_format": "Right %d",
        "remaining_cards_format": "%d cards left",
        "table_pile": "Current Trick",
        "table_waiting": "Waiting for a play",
        "recent_play_format": "Last played by %@",
        "my_hand": "My Hand",
        "selected_count_format": "Selected %d",
        "play": "Play",
        "next_hand": "Next Hand",
        "pass": "Pass",
        "declare_single": "Declare",
        "new_game": "New Game",
        "settings": "Settings",
        "rules": "Settings & Rules",
        "language": "Language",
        "round_result": "Round Result",
        "round_history": "Round History",
        "round_history_empty": "No round history yet",
        "move_history": "Move History",
        "move_history_empty": "No move history yet",
        "move_play_format": "Hand %d %@ played %@",
        "move_pass_format": "Hand %d %@ passed",
        "move_reason_suffix_format": " (AI: %@)",
        "round_col_hand": "Hand",
        "round_col_me": "Me",
        "round_col_left": "Left",
        "round_col_right": "Right",
        "round_result_line_format": "Hand %d %@: Me%+d Left%+d Right%+d",
        "hint_tap_new_game": "Tap \"New Game\" to begin",
        "hint_new_round_first_format": "New hand started. %@ leads",
        "hint_first_lead_no_pass": "Leader cannot pass",
        "hint_must_beat_no_pass": "You have a beating play. Passing is not allowed",
        "hint_must_beat_cycle_format": "A valid beating play exists (%d/%d selected)",
        "hint_drag_select_ready": "Long-press then drag to batch select",
        "hint_first_turn_need_3s": "First play must include 3 of Spades",
        "hint_must_play_highest_single_when_next_one_card": "When the next player has one card left, a single must be your highest",
        "hint_cannot_beat_top": "Cannot beat current top play",
        "hint_played_cards_format": "%@ played: %@",
        "hint_two_pass_reset_format": "Two players passed. %@ leads again",
        "hint_player_pass_format": "%@ passed",
        "voice_player_cannot_beat_format": "%@ passes",
        "hint_round_finish_format": "Round finished: %@ wins",
        "hint_restored_local_state": "Local progress restored",
        "hint_action_ready": "Select cards to play",
        "hint_declared_single": "Declared. Auto-plays on beatable singles, otherwise auto-passes.",
        "hint_waiting_player_format": "Waiting for %@ to play",
        "voice_declare_single": "I declare one card left",
        "hint_bomb_must_play": "Only a bomb can beat this play. You must play a bomb.",
        "confirm_new_game_title": "Start a new round?",
        "confirm_new_game_message": "Current round progress will be overwritten.",
        "confirm": "Confirm",
        "cancel": "Cancel",
        "rules_page_title": "Settings & Rules",
        "tab_rules": "Rules",
        "tab_settings": "Settings",
        "rules_deck_title": "1. Deck and Deal",
        "rules_deck_body": "This game uses 48 cards (2H, 2D, 2C, and AD removed). Three players get 16 cards each.",
        "rules_turn_title": "2. Turn Order",
        "rules_turn_body": "Only the first play of the game must include 3 of Spades. Play then proceeds in turn order. If two players pass, the last player who played leads the next trick.",
        "rules_play_title": "3. Valid Plays",
        "rules_play_body": "Valid plays: single, pair, straight, consecutive pairs, triple with two, airplane with wings, and bomb.",
        "rules_compare_title": "4. Comparison Rules",
        "rules_compare_body": "Only plays of the same type and card count can be compared by rank. Bombs beat non-bombs. Between bombs, higher rank wins.",
        "rules_must_title": "5. Pass Restriction",
        "rules_must_body": "If you can beat the current top play, passing is not allowed. Under Hunan Classic: if only a bomb can beat, you must play a bomb; if non-bomb options exist, playing a bomb is optional.",
        "rules_score_title": "6. Scoring",
        "rules_score_body": "At hand end, the winner gains the sum of both losers' penalties. Loser penalty: 0 with <=1 card left, 15 with 15 cards left, 30 with 16 cards left, otherwise equal to remaining cards. Bomb scoring is separate: when a bomb stands, bomber +20 and both opponents -10; if over-bombed by a higher bomb, the previous bomb score is canceled and the higher bomb settles with the same rule. Bombed players are marked with 💣 in history.",
        "rules_setting_title": "7. Rule Settings",
        "rules_setting_body": "Configure triple with one, triple only, mandatory bomb only when it is the sole beating play, and common presets.",
        "strategy_title": "Strategy Tips",
        "strategy_1_title": "Finish First",
        "strategy_1_body": "Shed loose low cards and weak pairs early so they do not block your final turns.",
        "strategy_2_title": "Watch One-Card Hands",
        "strategy_2_body": "When the next player has one card left, lead or beat with pressure instead of giving them an easy out.",
        "strategy_3_title": "Save Bombs for Swing Turns",
        "strategy_3_body": "A bomb can win control and change scoring, so it is strongest when it changes the hand's outcome.",
        "strategy_4_title": "Use Runs Cleanly",
        "strategy_4_body": "Straights and consecutive pairs reduce card count fast, but avoid breaking combinations you need later.",
        "rules_preset": "Preset",
        "rules_preset_hunanClassic": "Hunan Classic",
        "rules_preset_relaxed": "Relaxed",
        "rules_preset_bombPriority": "Bomb When Sole Beat",
        "rules_preset_custom": "Custom",
        "rules_allow_triple_with_one": "Allow Triple with One",
        "rules_allow_triple_without_wing": "Allow Triple Only",
        "rules_bomb_must_play": "Require Bomb Only When Sole Beat",
        "rules_ai_tuning_title": "AI Tuning (Dev)",
        "rules_ai_tuning_danger_threshold": "Danger threshold (opponent at one card)",
        "rules_ai_tuning_avoid_bomb_turns": "Bomb hold threshold (remaining turns)",
        "rules_ai_tuning_history_limit": "Move history cap",
        "rules_selfplay_title": "Self-play Export (Dev)",
        "rules_selfplay_enable": "Enable auto-run and export",
        "rules_selfplay_hands": "Self-play hands",
        "rules_selfplay_share_summary": "Share summary JSON",
        "rules_selfplay_share_unavailable": "No file available yet. Run self-play export first.",
        "rules_selfplay_share_latest_log": "Share latest game log JSON",
        "rules_selfplay_share_latest_log_unavailable": "No latest game log yet. Finish at least one hand first.",
        "rules_selfplay_share_detail": "Share full self-play detail JSON",
        "rules_selfplay_share_detail_unavailable": "No self-play details yet. Run self-play first.",
        "selfplay_status_running_format": "Self-play running: %d hands...",
        "selfplay_status_done_format": "Self-play complete. Exported: %@",
        "selfplay_status_done_with_detail_format": "Self-play finished. Summary: %@; Detail: %@",
        "selfplay_status_done_detail_only_format": "Self-play complete. Details exported: %@",
        "selfplay_status_failed": "Self-play export failed",
        "welcome_title": "Hunan Paodekuai",
        "welcome_subtitle": "Authentic rules, classic gameplay",
        "welcome_start_game": "Start Game",
        "voice_on": "Voice On",
        "voice_off": "Voice Off",
        "invalid_no_selection": "No card selected",
        "invalid_shape": "Invalid card combination",
        "voice_pair_prefix": "Pair of ",
        "voice_bomb_suffix": " bomb",
        "voice_straight": "Straight",
        "voice_triple": "Triple",
        "voice_triple_with_one": "Triple with one",
        "voice_triple_with_two": "Triple with two",
        "voice_airplane_with_wings": "Airplane with wings",
        "voice_consecutive_pairs": "Consecutive pairs",
        "voice_rank_a": "Ace",
        "voice_rank_t": "ten",
        "voice_rank_2": "Two",
        "voice_rank_j": "Jack",
        "voice_rank_q": "Queen",
        "speech_round_finish_format": "%@ finishes first.",
        "privacy_policy_title": "Privacy Policy",
        "privacy_policy_url": "https://paodekuai.pokerjudge.com/privacy-en.html",
        "about_title": "About"
    ]

    static func currentLanguage() -> AppLanguage {
        let raw = UserDefaults.standard.string(forKey: AppLanguage.storageKey)
        return AppLanguage(rawValue: raw ?? "") ?? .zhHans
    }

    static func text(_ key: String, language: AppLanguage? = nil) -> String {
        let resolved = language ?? currentLanguage()
        let dict = resolved == .en ? en : zhHans
        return dict[key] ?? key
    }

    static func format(_ key: String, language: AppLanguage? = nil, _ args: CVarArg...) -> String {
        let resolved = language ?? currentLanguage()
        let locale = resolved == .en ? Locale(identifier: "en_US") : Locale(identifier: "zh_Hans_CN")
        return String(format: text(key, language: resolved), locale: locale, arguments: args)
    }
}
